DROP TABLE IF EXISTS endpoint_hits;

create table if not exists endpoint_hits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    ip VARCHAR(31) NOT NULL,
    uri VARCHAR(255) NOT NULL,
    created TIMESTAMP NOT NULL
);

create index IF NOT EXISTS idx_endpoint_hits_app ON endpoint_hits (app);
create index IF NOT EXISTS idx_endpoint_hits_ip ON endpoint_hits (ip);
create index IF NOT EXISTS idx_endpoint_hits_uri ON endpoint_hits (uri);
create index IF NOT EXISTS idx_endpoint_hits_created ON endpoint_hits (created);